version: "3"
services:
  db:
    image: "postgres:12"
    container_name: "projector_db"
    ports:
      - "5432:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: .env
volumes:
  pgdata:
