// import useSWR from 'swr'
import Head from "next/head";
import client from "../lib/apollo-client";
import { withApollo } from "../lib/apollo";

import Layout from "../components/layout";

import Projects from "../components/projects";
import Members from "../components/members";
import Areas from "../components/areas";

import { GET_MEMBERS, GET_PROJECTS, GET_AREAS } from "../utils/queries";
import { Flex } from "@chakra-ui/core";

export async function getStaticProps() {
  // Props statically generated by the server
  // to pre-render page

  const members = await client.query({
    query: GET_MEMBERS,
  });

  const projects = await client.query({
    query: GET_PROJECTS,
  });

  const areas = await client.query({
    query: GET_AREAS,
  });

  return {
    props: {
      members: members.data.members,
      projects: projects.data.projects,
      areas: areas.data.area,
    },
  };
}

const Index = ({ members, projects, areas }) => {
  return (
    <>
      <Head>
        <title>Projector</title>
      </Head>
      <Layout home>
        <Flex padding="15px">
          <Projects projects={projects} />
          <Members members={members} />
          <Areas areas={areas} />
        </Flex>
      </Layout>
    </>
  );
};

export default Index;
